spring:
  profiles:
    active: "default"
  application:
    name: empapp

server:
  port: 8084

eureka:
  instance:
    prefer-ip-address: true

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8073/eureka/

management:
  tracing:
    sampling:
      probability: 1

  endpoints:
    web:
      exposure:
        include: "*"

  endpoint:
    shutdown:
      enabled: true

  info:
    env:
      enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
