apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp-deploy
  annotations:
    kubernetes.io/change-cause: "Deploying v1.4"
spec:
  minReadySeconds: 10
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: orderapp
  replicas: 3
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
      - name: orderapp
        image: beingnitesh95/orderapp:1.4
        ports:
        - name: "app-port"
          containerPort: 8081