spring:
    application:
        name: eureka

server:
    port: 8073

eureka:
    instance:
        hostname: localhost

    client:
        fetch-registry: false
        register-with-eureka: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
    tracing:
        sampling:
            probability: 1.0

    endpoints:
        web:
            exposure:
                include: "*"

    health:
        livenessState:
            enabled: true
        readinessState:
            enabled: true

    endpoint:
        health:
            enabled: true

logging:
    pattern:
        level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"
