spring:
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: productapp
server:
  port: 8083
PRODUCT_APP_ERROR_500: "pls try after some time"


key:
  message: "it is a default profile"

account:
  message: "welcome to productapp default profile"
  contactDetails:
    name: "nitesh"
    email: "nitesh.default@gmail.com"
  onCallSupport:
    -054645464556
    -075765777677

management:
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: "*"