spring:
  application:
    name: orderapp
server:
  port: 8081

apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderapp-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderapp
  template:
    metadata:
      labels:
        app: orderapp
    spec:
      containers:
        - name: orderapp
          image: beingnitesh95/orderapp:1.12
          ports:
            - name: "orderapp-port"
              containerPort: 8081

management:
  endpoint:
    health:
      probes:
        enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true